[versions]
agp = "8.13.2" #8.12.0
alertKmp = "2.0.0"
android-compileSdk = "36"
android-minSdk = "24"
#noinspection OldTargetApi
android-targetSdk = "35"
androidx-activity = "1.13.0" #1.12.4
androidx-lifecycle = "2.10.0" #2.9.6
bignum = "0.3.10"
coilCompose = "3.4.0" #3.3.0
#composeMultiplatform = "1.9.3" #1.9.3
composemediaplayer = "0.8.7" #0.8.6
compose-multiplatform-adaptive = "1.3.0-alpha06"
compose-multiplatform-lifecycle = "2.10.0"
composeMultiplatform = "1.10.3" #1.10.2
composeMultiplatformMediaPlayer = "1.0.53" #1.0.52
composePipette = "2.0.0"
composePlaceholderMaterial3 = "1.0.12"
composeWebviewMultiplatform = "2.0.3" #2.0.2
compottieLite = "2.1.0" #2.0.3
datatableMaterial3 = "0.12.0" #0.11.7
filekitCore = "0.13.0" #0.12.0
haze = "1.7.2" #1.7.2
jmail = "2.1.0" #2.0.2
koinCore = "4.2.0" #4.1.1
kotlin = "2.3.20" #2.3.0
kotlinx-coroutines = "1.10.2"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.10.0" #1.9.0
kscan = "0.8.1"
ktor = "3.4.2" #3.4.1
libphonenumber = "0.1.9" #0.1.8
materialIconsCore = "1.7.3"
multiplatformSettings = "1.3.0"
navigation3Runtime = "1.1.0-rc01" #1.1.0-beta01
multiplatform-nav3-ui = "1.0.0-alpha06"
navigationCompose = "2.9.2" #2.9.1
pagingRuntime = "3.4.2" #3.4.0-rc01
reorderable = "3.0.0"
richeditorCompose = "1.0.0-rc13"
securityCrypto = "1.1.0"
sonner = "0.3.9"
tableCore = "1.8.1" #1.7.15
uiTooling = "1.10.3" #1.10.2
webcam = "0.3.12"
zoomable = "2.11.1" #2.9.0
zxing = "3.5.4"
zxingAndroid = "4.3.0"

[libraries]
alert-kmp = { module = "io.github.khubaibkhan4:alert-kmp", version.ref = "alertKmp" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3Runtime" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingRuntime" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingRuntime" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilCompose" }
compose-multiplatform-media-player = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "composeMultiplatformMediaPlayer" }
compose-placeholder-material3 = { module = "com.eygraber:compose-placeholder-material3", version.ref = "composePlaceholderMaterial3" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
composePipette = { module = "dev.zt64.compose.pipette:compose-pipette", version.ref = "composePipette" }
composemediaplayer = { module = "io.github.kdroidfilter:composemediaplayer", version.ref = "composemediaplayer" }
compottie-lite = { module = "io.github.alexzhirkevich:compottie-lite", version.ref = "compottieLite" }
datatable-material3 = { module = "com.seanproctor:datatable-material3", version.ref = "datatableMaterial3" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekitCore" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekitCore" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekitCore" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
jmail = { module = "com.sanctionco.jmail:jmail", version.ref = "jmail" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinCore" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kmp-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kscan = { module = "io.github.ismai117:KScan", version.ref = "kscan" }
libphonenumber = { module = "io.github.luca992.libphonenumber-kotlin:libphonenumber", version.ref = "libphonenumber" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsCore" }
jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "multiplatform-nav3-ui" }
jetbrains-material3-adaptiveNavigation3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "compose-multiplatform-adaptive" }
jetbrains-lifecycle-viewmodelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-multiplatform-lifecycle" }
journeyapps-zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref= "zxingAndroid"}
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
russhwolf-multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
webcam-capture = { module = "com.github.sarxos:webcam-capture", version.ref = "webcam" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxing" }

# Ktor core & plugins
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

# Engines per platform
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
table-core = { module = "ua.wwind.table-kmp:table-core", version.ref = "tableCore" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
#android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }