workflows:
  ios-kmp:
    name: Build iOS KMP App
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "org.dsqrwym.pgdm"
        APP_NAME: "Plataforma Gestio-n Distribucio-n  Mayorista"
    scripts:
      - name: List Xcode schemes
        script: |
          xcodebuild -list -project "Front/Plataforma Gestio-n Distribucio-n  Mayorista/iosApp/iosApp.xcodeproj"
      - name: Install dependencies
        script: |
          brew install cocoapods || true
          pod install --project-directory="Front/Plataforma Gestio-n Distribucio-n  Mayorista/iosApp"
      - name: Build iOS framework from shared module
        script: |
          "Front/Plataforma Gestio-n Distribucio-n  Mayorista/gradlew" :shared:syncFramework
      - name: Build iOS app
        script: |
          xcodebuild -project "Front/Plataforma Gestio-n Distribucio-n  Mayorista/iosApp/iosApp.xcodeproj" \
            -scheme iosApp \
            -sdk iphoneos -configuration release archive \
            -archivePath $HOME/build/$APP_NAME.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $HOME/build/$APP_NAME.xcarchive \
            -exportOptionsPlist "Front/Plataforma Gestio-n Distribucio-n  Mayorista/iosApp/exportOptions.plist" \
            -exportPath $HOME/build/IPA
    artifacts:
      - build/IPA/*.ipa
