services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    env_file:
      - ./.env
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
    ports:
      - "2000:2000"  # 将容器的 2000 端口映射到宿主机的 2000