    -- Data source / 数据来源: https://es.wikipedia.org/wiki/Anexo:Provincias_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a
INSERT INTO
    public.provinces (country_iso, name, name_local)
VALUES
    (724, 'Álava', 'Álava'),
    (724, 'Albacete', 'Albacete'),
    (724, 'Alicante', 'Alicante'),
    (724, 'Almería', 'Almería'),
    (724, 'Asturias', 'Asturias'),
    (724, 'Ávila', 'Ávila'),
    (724, 'Badajoz', 'Badajoz'),
    (724, 'Barcelona', 'Barcelona'),
    (724, 'Burgos', 'Burgos'),
    (724, 'Cáceres', 'Cáceres'),
    (724, 'Cádiz', 'Cádiz'),
    (724, 'Cantabria', 'Cantabria'),
    (724, 'Castellón', 'Castellón'),
    (724, 'Ceuta', 'Ceuta'),
    (724, 'Ciudad Real', 'Ciudad Real'),
    (724, 'Córdoba', 'Córdoba'),
    (724, 'Cuenca', 'Cuenca'),
    (724, 'Gerona', 'Girona'),
    (724, 'Granada', 'Granada'),
    (724, 'Guadalajara', 'Guadalajara'),
    (724, 'Guipúzcoa', 'Guipúzcoa'),
    (724, 'Huelva', 'Huelva'),
    (724, 'Huesca', 'Huesca'),
    (724, 'Islas Baleares', 'Illes Balears'),
    (724, 'Jaén', 'Jaén'),
    (724, 'La Coruña', 'A Coruña'),
    (724, 'La Rioja', 'La Rioja'),
    (724, 'Las Palmas', 'Las Palmas'),
    (724, 'León', 'León'),
    (724, 'Lérida', 'Lleida'),
    (724, 'Lugo', 'Lugo'),
    (724, 'Madrid', 'Madrid'),
    (724, 'Málaga', 'Málaga'),
    (724, 'Melilla', 'Melilla'),
    (724, 'Murcia', 'Murcia'),
    (724, 'Navarra', 'Navarra'),
    (724, 'Orense', 'Ourence'),
    (724, 'Palencia', 'Palencia'),
    (724, 'Pontevedra', 'Pontevedra'),
    (724, 'Salamanca', 'Salamanca'),
    (724, 'Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'),
    (724, 'Segovia', 'Segovia'),
    (724, 'Sevilla', 'Sevilla'),
    (724, 'Soria', 'Soria'),
    (724, 'Tarragona', 'Tarragona'),
    (724, 'Teruel', 'Teruel'),
    (724, 'Toledo', 'Toledo'),
    (724, 'Valencia', 'Valencia'),
    (724, 'Valladolid', 'Valladolid'),
    (724, 'Vizcaya', 'Bizkaia'),
    (724, 'Zamora', 'Zamora'),
    (724, 'Zaragoza', 'Zaragoza');