// 标准化文件模块错误码：用于前端区分不同失败原因，便于精确提示与控制流程
export const FILE_ERROR = {
  // 文件不存在
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  // 文件不是视频类型
  FILE_NOT_VIDEO: 'FILE_NOT_VIDEO',
  // 无权限访问该文件
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  // 视频播放 token 无效
  VIDEO_PLAY_TOKEN_INVALID: 'VIDEO_PLAY_TOKEN_INVALID',
  // 视频播放 token 已过期
  VIDEO_PLAY_TOKEN_EXPIRED: 'VIDEO_PLAY_TOKEN_EXPIRED',
  // 视频播放 token 类型不匹配
  VIDEO_PLAY_TOKEN_TYPE_MISMATCH: 'VIDEO_PLAY_TOKEN_TYPE_MISMATCH',
  // 视频播放 token 与文件 ID 不匹配
  VIDEO_PLAY_TOKEN_FILE_MISMATCH: 'VIDEO_PLAY_TOKEN_FILE_MISMATCH',
  VIDEO_PLAY_TOKEN_PRODUCT_MISMATCH: 'VIDEO_PLAY_TOKEN_PRODUCT_MISMATCH',
  // 视频播放 token 已被撤销
  VIDEO_PLAY_TOKEN_REVOKED: 'VIDEO_PLAY_TOKEN_REVOKED',
  // 缺少 playToken 参数
  VIDEO_PLAY_TOKEN_MISSING: 'VIDEO_PLAY_TOKEN_MISSING',
} as const;
