#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx5120M
kotlin.compiler.execution.strategy=daemon
#Gradle
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
gradle.user.home=D\:\\Gradle
org.gradle.parallel=true
org.gradle.configuration-cache.problems=warn
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.caching.debug=false
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=false
android.newDsl=false
