-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."AddressType" AS ENUM('DELIVERY', 'INVOICE', 'STORE');--> statement-breakpoint
CREATE TYPE "public"."DeliveryStatus" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED');--> statement-breakpoint
CREATE TYPE "public"."ProductStatus" AS ENUM('ACTIVE', 'INACTIVE');--> statement-breakpoint
CREATE TYPE "public"."SaleVariant" AS ENUM('UNIT', 'BOX', 'PACK');--> statement-breakpoint
CREATE TYPE "public"."UserRole" AS ENUM('WHOLESALER', 'RETAILER', 'SUPPORT', 'DELIVERY', 'WAREHOUSE', 'ADMIN', 'SUPERADMIN');--> statement-breakpoint
CREATE TYPE "public"."UserStatus" AS ENUM('PENDING_VERIFICATION', 'INACTIVE', 'ACTIVE', 'PENDING_REVIEW', 'APPROVED', 'BANNED');--> statement-breakpoint
CREATE SEQUENCE "public"."seq_deliveryman_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_retailer_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_support_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_warehouse_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_wholesaler_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_admin_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."seq_superadmin_id" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "provinces" (
	"id" serial PRIMARY KEY NOT NULL,
	"country_iso" smallint NOT NULL,
	"name" varchar(100) NOT NULL,
	"name_local" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"iso_alpha2" char(2) NOT NULL,
	"iso_alpha3" char(3) NOT NULL,
	"iso_numeric" smallint PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"name_local" varchar(100) NOT NULL,
	"currency_id" smallint,
	CONSTRAINT "countries_iso_alpha2_key" UNIQUE("iso_alpha2"),
	CONSTRAINT "countries_iso_alpha3_key" UNIQUE("iso_alpha3"),
	CONSTRAINT "countries_iso_numeric_key" UNIQUE("iso_numeric")
);
--> statement-breakpoint
CREATE TABLE "variant_products" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "variant_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"product_id" bigint NOT NULL,
	"type_sale" "SaleVariant" NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"price_iva" numeric(10, 2) NOT NULL,
	"available_stock" integer NOT NULL,
	"sort" smallint NOT NULL,
	"attributes" jsonb,
	"status" "ProductStatus" DEFAULT 'ACTIVE' NOT NULL,
	"product_code" varchar(50) NOT NULL,
	"reserved_stock" integer DEFAULT 0 NOT NULL,
	"low_stock_threshold" integer DEFAULT 0 NOT NULL,
	"sale_unit_qty" integer DEFAULT 1 NOT NULL,
	"min_order_qty" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"created_by" uuid NOT NULL,
	"updated_by" uuid,
	CONSTRAINT "variant_available_stock_check" CHECK (available_stock >= 0),
	CONSTRAINT "variant_low_stock_threshold_check" CHECK (low_stock_threshold >= 0),
	CONSTRAINT "variant_min_order_qty_check" CHECK (min_order_qty >= 1),
	CONSTRAINT "variant_price_check" CHECK (price >= (0)::numeric),
	CONSTRAINT "variant_price_iva_check" CHECK (price_iva >= (0)::numeric),
	CONSTRAINT "variant_reserved_stock_check" CHECK (reserved_stock >= 0),
	CONSTRAINT "variant_sale_unit_qty_check" CHECK (sale_unit_qty >= 1),
	CONSTRAINT "variant_sort_check" CHECK (sort >= 0)
);
--> statement-breakpoint
CREATE TABLE "files" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file_name" varchar NOT NULL,
	"file_hash" varchar(64) NOT NULL,
	"mime_type" varchar(128) NOT NULL,
	"file_size" bigint NOT NULL,
	"storage_key" text NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"to_delete" boolean DEFAULT false NOT NULL,
	CONSTRAINT "files_file_hash_key" UNIQUE("file_hash"),
	CONSTRAINT "files_file_name_check" CHECK ((file_name)::text ~* '^[^\\/:\*\?"<>\|]{1,255}\.[a-z0-9]+$'::text)
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid,
	"name" varchar(50) NOT NULL,
	"iva" numeric(5, 2),
	"parent_id" bigint,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"level" smallint NOT NULL,
	"name_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((name)::text)) STORED,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"created_by" uuid,
	"updated_by" uuid,
	"version" bigint DEFAULT 1 NOT NULL,
	CONSTRAINT "categories_iva_check" CHECK (iva >= (0)::numeric),
	CONSTRAINT "categories_level_check" CHECK ((level >= 1) AND (level <= 3))
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" serial PRIMARY KEY NOT NULL,
	"province_id" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"name_local" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cart_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cart_id" bigint NOT NULL,
	"variant_products_id" bigint,
	"quantity" integer NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "cart_details_quantity_check" CHECK (quantity > 0)
);
--> statement-breakpoint
ALTER TABLE "cart_details" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chat_panels" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_panel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discounts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"name" varchar NOT NULL,
	"type_value" jsonb NOT NULL,
	"applies_to_all" boolean DEFAULT false NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"status" smallint DEFAULT '1' NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "message_files" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"message_id" bigint NOT NULL,
	"file_id" bigint NOT NULL,
	"sort" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "products_files" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_id" bigint NOT NULL,
	"file_id" bigint NOT NULL,
	"sort" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "carts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cart_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "carts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "configurations" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"language" varchar(10) DEFAULT 'en' NOT NULL,
	"timezone" varchar(32) DEFAULT 'UTC' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "configurations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "deliveries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"delivery_person" uuid,
	"status" "DeliveryStatus" DEFAULT 'PENDING' NOT NULL,
	"start_time" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"end_time" timestamp,
	"notes" text NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL
);
--> statement-breakpoint
ALTER TABLE "deliveries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "products" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"name" varchar(50) NOT NULL,
	"title" varchar(100),
	"description" text,
	"iva" numeric(5, 2) NOT NULL,
	"status" "ProductStatus" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"product_code" varchar(50) NOT NULL,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"created_by" uuid NOT NULL,
	"updated_by" uuid,
	"name_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((name)::text)) STORED,
	"title_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((title)::text)) STORED,
	"version" bigint DEFAULT 1 NOT NULL,
	CONSTRAINT "products_iva_check" CHECK (iva >= (0)::numeric)
);
--> statement-breakpoint
CREATE TABLE "currencies" (
	"iso_numeric" smallint PRIMARY KEY NOT NULL,
	"iso_alpha3" char(3) NOT NULL,
	"symbol" varchar(5) NOT NULL,
	"decimal_digits" smallint NOT NULL,
	CONSTRAINT "currencies_iso_alpha3_key" UNIQUE("iso_alpha3")
);
--> statement-breakpoint
CREATE TABLE "directions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "directions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"type" "AddressType" DEFAULT 'STORE' NOT NULL,
	"country_iso" smallint NOT NULL,
	"province_id" integer NOT NULL,
	"city_id" integer NOT NULL,
	"street" varchar(200) NOT NULL,
	"zip_code" varchar(10) NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "delivery_timeline" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "delivery_timeline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"delivery_id" bigint,
	"status" "DeliveryStatus" NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL
);
--> statement-breakpoint
ALTER TABLE "delivery_timeline" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "order_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"product_code" varchar(50) NOT NULL,
	"variant_product_id" bigint NOT NULL,
	"quantity" integer NOT NULL,
	"unit_price" numeric(10, 2) NOT NULL,
	"unit_price_iva" numeric(10, 2) NOT NULL,
	"subtotal" numeric(12, 2) NOT NULL,
	"iva" numeric(10, 2) NOT NULL,
	"discount_applied" numeric(10, 2) NOT NULL,
	"attributes" jsonb NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "order_details" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"chat_panel_id" bigint NOT NULL,
	"sender_id" uuid DEFAULT '00000000-0000-0000-0000-000000000000',
	"reply_to" bigint DEFAULT '-1',
	"content" text,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"title" varchar(100) NOT NULL,
	"message" text NOT NULL,
	"type" smallint NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"click_action" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"session_id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"user_id" uuid NOT NULL,
	"device_name" varchar(150) NOT NULL,
	"device_finger" varchar(255) NOT NULL,
	"user_agent" text NOT NULL,
	"revoked" boolean DEFAULT false NOT NULL,
	"last_ip" varchar(50) NOT NULL,
	"refresh_token" text,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"last_active" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "unique_device_finger_user" UNIQUE("user_id","device_finger")
);
--> statement-breakpoint
ALTER TABLE "user_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "verification_tokens" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"user_id" uuid NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"is_used" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "verification_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"retailer_id" uuid,
	"wholesaler_id" uuid,
	"status" smallint DEFAULT '1' NOT NULL,
	"payment_method" smallint NOT NULL,
	"shipping_address" bigint,
	"notes" varchar(500),
	"discount_total" numeric(12, 2) NOT NULL,
	"subtotal" numeric(12, 2) NOT NULL,
	"total" numeric(12, 2) NOT NULL,
	"iva_total" numeric(12, 2) NOT NULL,
	"discount_log" jsonb NOT NULL,
	"estimated_date" timestamp,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text)
);
--> statement-breakpoint
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"user_id" text,
	"first_name" varchar(50),
	"last_name" varchar(60),
	"username" varchar(50),
	"password" text NOT NULL,
	"email" varchar(255) NOT NULL,
	"telephone" varchar(25),
	"status" "UserStatus" DEFAULT 'PENDING_VERIFICATION' NOT NULL,
	"profile" jsonb,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"role" "UserRole" NOT NULL,
	"cif" varchar(20),
	"updated_by" uuid,
	CONSTRAINT "users_user_id_key" UNIQUE("user_id"),
	CONSTRAINT "users_username_key" UNIQUE("username"),
	CONSTRAINT "users_email_key" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_uploads" (
	"user_id" uuid NOT NULL,
	"file_id" bigint NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "user_uploads_pkey" PRIMARY KEY("user_id","file_id")
);
--> statement-breakpoint
CREATE TABLE "chat_participants" (
	"user_id" uuid NOT NULL,
	"chat_panel_id" bigint NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	CONSTRAINT "chat_participants_pkey" PRIMARY KEY("user_id","chat_panel_id")
);
--> statement-breakpoint
CREATE TABLE "product_categories" (
	"product_id" bigint NOT NULL,
	"category_id" bigint NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	CONSTRAINT "product_categories_pkey" PRIMARY KEY("product_id","category_id")
);
--> statement-breakpoint
CREATE TABLE "category_translations" (
	"category_id" bigint NOT NULL,
	"lang_code" varchar(10) NOT NULL,
	"name" varchar(50) NOT NULL,
	"name_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((name)::text)) STORED,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"updated_by" uuid,
	CONSTRAINT "pk_category_translations" PRIMARY KEY("category_id","lang_code")
);
--> statement-breakpoint
CREATE TABLE "product_translations" (
	"product_id" bigint NOT NULL,
	"lang_code" varchar(10) NOT NULL,
	"name" varchar(50) NOT NULL,
	"title" varchar(100),
	"description" text,
	"name_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((name)::text)) STORED,
	"title_unaccent" text GENERATED ALWAYS AS (immutable_unaccent((title)::text)) STORED,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text),
	"updated_by" uuid,
	CONSTRAINT "pk_product_translations" PRIMARY KEY("product_id","lang_code")
);
--> statement-breakpoint
ALTER TABLE "provinces" ADD CONSTRAINT "provinces_country_iso_fkey" FOREIGN KEY ("country_iso") REFERENCES "public"."countries"("iso_numeric") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "countries" ADD CONSTRAINT "countries_currency_id_fkey" FOREIGN KEY ("currency_id") REFERENCES "public"."currencies"("iso_numeric") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "variant_products" ADD CONSTRAINT "variant_products_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "variant_products" ADD CONSTRAINT "variant_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "variant_products" ADD CONSTRAINT "variant_products_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_province_id_fkey" FOREIGN KEY ("province_id") REFERENCES "public"."provinces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_details" ADD CONSTRAINT "cart_details_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "public"."carts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_details" ADD CONSTRAINT "cart_details_variant_products_id_fkey" FOREIGN KEY ("variant_products_id") REFERENCES "public"."variant_products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discounts" ADD CONSTRAINT "discounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_files" ADD CONSTRAINT "message_files_file_id_fkey" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_files" ADD CONSTRAINT "message_files_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products_files" ADD CONSTRAINT "products_files_file_id_fkey" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products_files" ADD CONSTRAINT "products_files_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "carts" ADD CONSTRAINT "carts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "configurations" ADD CONSTRAINT "configurations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_delivery_person_fkey" FOREIGN KEY ("delivery_person") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_country_iso_fkey" FOREIGN KEY ("country_iso") REFERENCES "public"."countries"("iso_numeric") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_province_id_fkey" FOREIGN KEY ("province_id") REFERENCES "public"."provinces"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delivery_timeline" ADD CONSTRAINT "delivery_timeline_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "public"."deliveries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_details" ADD CONSTRAINT "order_details_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_details" ADD CONSTRAINT "order_details_variant_product_id_fkey" FOREIGN KEY ("variant_product_id") REFERENCES "public"."variant_products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_chat_panel_id_fkey" FOREIGN KEY ("chat_panel_id") REFERENCES "public"."chat_panels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_reply_to_fkey" FOREIGN KEY ("reply_to") REFERENCES "public"."messages"("id") ON DELETE set default ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON DELETE set default ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "fk_user_sessions_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "verification_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_shipping_address_fkey" FOREIGN KEY ("shipping_address") REFERENCES "public"."directions"("id") ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_wholesaler_id_fkey" FOREIGN KEY ("wholesaler_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_uploads" ADD CONSTRAINT "user_uploads_file_id_fkey" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_uploads" ADD CONSTRAINT "user_uploads_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_participants" ADD CONSTRAINT "chat_participants_chat_panel_id_fkey" FOREIGN KEY ("chat_panel_id") REFERENCES "public"."chat_panels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_participants" ADD CONSTRAINT "chat_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_categories" ADD CONSTRAINT "product_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_categories" ADD CONSTRAINT "product_categories_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "category_translations" ADD CONSTRAINT "category_translations_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "category_translations" ADD CONSTRAINT "fk_category_translations_category_id" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_translations" ADD CONSTRAINT "fk_product_translations_product_id" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_translations" ADD CONSTRAINT "product_translations_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_files_created_at" ON "files" USING btree ("created_at" timestamp_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "categories_name_unique_public" ON "categories" USING btree ("name" text_ops) WHERE (user_id IS NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "categories_user_name_unique_private" ON "categories" USING btree ("user_id" text_ops,"name" text_ops) WHERE (user_id IS NOT NULL);--> statement-breakpoint
CREATE INDEX "idx_categories_name_unaccent" ON "categories" USING btree (lower(name_unaccent) text_ops);--> statement-breakpoint
CREATE INDEX "idx_message_files_file_id" ON "message_files" USING btree ("file_id" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_products_files_file_id" ON "products_files" USING btree ("file_id" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_products_files_product_id" ON "products_files" USING btree ("product_id" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_products_name_unaccent" ON "products" USING btree (lower(name_unaccent) text_ops);--> statement-breakpoint
CREATE INDEX "idx_products_title_unaccent" ON "products" USING btree (lower(title_unaccent) text_ops);--> statement-breakpoint
CREATE INDEX "password_reset_tokens_token_idx" ON "verification_tokens" USING btree ("token" text_ops);--> statement-breakpoint
CREATE INDEX "password_reset_tokens_user_id_idx" ON "verification_tokens" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "verification_tokens_user_id_token_idx" ON "verification_tokens" USING btree ("user_id" text_ops,"token" text_ops);--> statement-breakpoint
CREATE INDEX "idx_category_translations_lang_code" ON "category_translations" USING btree ("lang_code" text_ops);--> statement-breakpoint
CREATE INDEX "idx_category_translations_name_unaccent" ON "category_translations" USING btree (lower(name_unaccent) text_ops);--> statement-breakpoint
CREATE INDEX "idx_product_translations_name_unaccent" ON "product_translations" USING btree (lower(name_unaccent) text_ops);--> statement-breakpoint
CREATE INDEX "idx_product_translations_title_unaccent" ON "product_translations" USING btree (lower(title_unaccent) text_ops);
*/