--
-- PostgreSQL database dump
--

\restrict RoDyhYsshoz4OnbrfFPJckgV42RIOPaHefEDAhyKguQoOldSiPYFVafFZHylDjF

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: AddressType; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."AddressType" AS ENUM (
    'DELIVERY',
    'INVOICE',
    'STORE'
);


--
-- Name: DeliveryStatus; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."DeliveryStatus" AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED'
);


--
-- Name: OrderStatus; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."OrderStatus" AS ENUM (
    'PENDING',
    'ACCEPTED',
    'REJECTED',
    'CANCELLED'
);


--
-- Name: ProductStatus; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."ProductStatus" AS ENUM (
    'ACTIVE',
    'INACTIVE'
);


--
-- Name: TYPE "ProductStatus"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TYPE public."ProductStatus" IS '产品状态';


--
-- Name: SaleVariant; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."SaleVariant" AS ENUM (
    'UNIT',
    'BOX',
    'PACK'
);


--
-- Name: TYPE "SaleVariant"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TYPE public."SaleVariant" IS '产品销售变体的类型，分别为散卖，箱和包';


--
-- Name: UserRole; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."UserRole" AS ENUM (
    'WHOLESALER',
    'RETAILER',
    'SUPPORT',
    'DELIVERY',
    'WAREHOUSE',
    'ADMIN',
    'SUPERADMIN'
);


--
-- Name: UserStatus; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."UserStatus" AS ENUM (
    'PENDING_VERIFICATION',
    'INACTIVE',
    'ACTIVE',
    'PENDING_REVIEW',
    'APPROVED',
    'BANNED'
);


--
-- Name: TYPE "UserStatus"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TYPE public."UserStatus" IS '用户状态';


--
-- Name: generate_user_id(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.generate_user_id() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE 
    acronym TEXT;
    seq_num INT;
BEGIN
    IF OLD.status = 'PENDING_VERIFICATION' 
       AND NEW.status IS DISTINCT FROM 'PENDING_VERIFICATION'
       AND NEW.user_id IS NULL THEN
        CASE NEW.role
            WHEN 'WHOLESALER' THEN
                acronym := 'WHO';
                seq_num := nextval('seq_wholesaler_id');
            WHEN 'RETAILER' THEN
                acronym := 'RET';
                seq_num := nextval('seq_retailer_id');
            WHEN 'SUPPORT' THEN
                acronym := 'SUP';
                seq_num := nextval('seq_support_id');
            WHEN 'DELIVERY' THEN
                acronym := 'DEL';
                seq_num := nextval('seq_deliveryman_id');
            WHEN 'WAREHOUSE' THEN
                acronym := 'WAR';
                seq_num := nextval('seq_warehouse_id');
            WHEN 'ADMIN' THEN
                acronym := 'ADM';
                seq_num := nextval('seq_admin_id');
            WHEN 'SUPERADMIN' THEN
                acronym := 'SADM';
                seq_num := nextval('seq_superadmin_id');
            ELSE
                RAISE EXCEPTION 'Unknown role %', NEW.role;
        END CASE;

        NEW.user_id := acronym || LPAD(seq_num::TEXT, 3, '0');
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: immutable_unaccent(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.immutable_unaccent(text) RETURNS text
    LANGUAGE sql IMMUTABLE
    AS $_$
SELECT unaccent('public.unaccent', $1);
$_$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_details (
    id bigint NOT NULL,
    cart_id bigint NOT NULL,
    variant_products_id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    CONSTRAINT cart_details_quantity_check CHECK (((quantity >= 1) AND (quantity <= 1000000)))
);


--
-- Name: cart_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    retailer_id uuid NOT NULL,
    wholesaler_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    CONSTRAINT carts_user_wholesaler_different CHECK ((retailer_id <> wholesaler_id))
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    user_id uuid,
    name character varying(50) NOT NULL,
    iva numeric(5,2),
    parent_id bigint,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    level smallint NOT NULL,
    name_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((name)::text)) STORED,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    created_by uuid,
    updated_by uuid,
    version bigint DEFAULT 1 NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT categories CHECK (((iva >= (0)::numeric) AND (iva <= (100)::numeric))),
    CONSTRAINT categories_level_check CHECK (((level >= 1) AND (level <= 3)))
);


--
-- Name: TABLE categories; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.categories IS '类别分为公共和私人 / categorías son públicos o privados';


--
-- Name: COLUMN categories.user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.categories.user_id IS '如果未空则代表为公共';


--
-- Name: COLUMN categories.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.categories.name IS '名字';


--
-- Name: COLUMN categories.level; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.categories.level IS '嵌套层级，最多三层即1->2->3';


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_translations (
    category_id bigint NOT NULL,
    lang_code character varying(10) NOT NULL,
    name character varying(50) NOT NULL,
    name_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((name)::text)) STORED,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_by uuid
);


--
-- Name: chat_panels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_panels (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: TABLE chat_panels; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.chat_panels IS '聊天界面或会话 / Sesión de Chat';


--
-- Name: chat_panel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_panels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_participants (
    user_id uuid NOT NULL,
    chat_panel_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text)
);


--
-- Name: TABLE chat_participants; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.chat_participants IS '连接用户和聊天会话 / Conectar usuarios y charlas';


--
-- Name: cities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    province_id integer NOT NULL,
    name character varying(100) NOT NULL,
    name_local character varying(100) NOT NULL
);


--
-- Name: COLUMN cities.province_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cities.province_id IS '所属省份 ID，外键关联 provinces 表';


--
-- Name: COLUMN cities.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cities.name IS '城市英文名称';


--
-- Name: COLUMN cities.name_local; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cities.name_local IS '城市本地名称';


--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.cities_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.cities_id_seq OWNED BY public.cities.id;


--
-- Name: configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configurations (
    user_id uuid NOT NULL,
    language character varying(10) DEFAULT 'en'::character varying NOT NULL,
    timezone character varying(32) DEFAULT 'UTC'::character varying NOT NULL
);


--
-- Name: COLUMN configurations.language; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.configurations.language IS 'BCP-47 Code';


--
-- Name: COLUMN configurations.timezone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.configurations.timezone IS 'IANA时区名字';


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    iso_alpha2 character(2) NOT NULL,
    iso_alpha3 character(3) NOT NULL,
    iso_numeric smallint NOT NULL,
    name character varying(100) NOT NULL,
    name_local character varying(100) NOT NULL,
    currency_id smallint
);


--
-- Name: COLUMN countries.iso_alpha2; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.iso_alpha2 IS 'ISO 3166-1 alpha-2 国家代码，两位字符';


--
-- Name: COLUMN countries.iso_alpha3; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.iso_alpha3 IS 'ISO 3166-1 alpha-3 国家代码，三位字符';


--
-- Name: COLUMN countries.iso_numeric; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.iso_numeric IS 'ISO 3166-1 数字代码';


--
-- Name: COLUMN countries.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.name IS '国家英文官方名称';


--
-- Name: COLUMN countries.name_local; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.name_local IS '国家本地语言名称';


--
-- Name: COLUMN countries.currency_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries.currency_id IS '使用的货币';


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencies (
    iso_numeric smallint NOT NULL,
    iso_alpha3 character(3) NOT NULL,
    symbol character varying(5) NOT NULL,
    decimal_digits smallint NOT NULL
);


--
-- Name: deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliveries (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    delivery_person uuid,
    status public."DeliveryStatus" DEFAULT 'PENDING'::public."DeliveryStatus" NOT NULL,
    start_time timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    end_time timestamp without time zone,
    notes text NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);


--
-- Name: TABLE deliveries; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.deliveries IS '送货表';


--
-- Name: COLUMN deliveries.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.deliveries.status IS '0=等待配送， 1=正在配送， 2=配送完成';


--
-- Name: COLUMN deliveries.start_time; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.deliveries.start_time IS '开始时间';


--
-- Name: COLUMN deliveries.end_time; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.deliveries.end_time IS '结束时间';


--
-- Name: deliveries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliveries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_timeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_timeline (
    id bigint NOT NULL,
    delivery_id bigint,
    status public."DeliveryStatus" NOT NULL,
    notes text,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);


--
-- Name: TABLE delivery_timeline; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.delivery_timeline IS '配送时间线';


--
-- Name: COLUMN delivery_timeline.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.delivery_timeline.status IS '0=等待配送， 1=正在配送， 2=配送完成';


--
-- Name: delivery_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: directions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.directions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    type public."AddressType" DEFAULT 'STORE'::public."AddressType" NOT NULL,
    country_iso smallint NOT NULL,
    province_id integer NOT NULL,
    city_id integer NOT NULL,
    street character varying(200) NOT NULL,
    zip_code character varying(10) NOT NULL,
    latitude double precision,
    longitude double precision,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone
);


--
-- Name: COLUMN directions.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.directions.type IS '地址类型';


--
-- Name: directions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.directions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.directions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discounts (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    name character varying NOT NULL,
    type_value jsonb NOT NULL,
    applies_to_all boolean DEFAULT false NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status smallint DEFAULT '1'::smallint NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: TABLE discounts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.discounts IS '折扣';


--
-- Name: COLUMN discounts.type_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.discounts.type_value IS '先做：减百分比，满金额减少固定金额，满金额减少百分比';


--
-- Name: COLUMN discounts.applies_to_all; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.discounts.applies_to_all IS '是否给其名下所有的产品';


--
-- Name: discounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.discounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_sequences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_sequences (
    owner_id uuid NOT NULL,
    document_type character varying(10) NOT NULL,
    year smallint NOT NULL,
    current_value integer DEFAULT 0 NOT NULL,
    CONSTRAINT document_sequences_current_value_check CHECK ((current_value >= 0)),
    CONSTRAINT document_sequences_year_check CHECK (((year >= 2000) AND (year <= 9999)))
);


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id bigint NOT NULL,
    file_name character varying NOT NULL,
    file_hash character varying(64) NOT NULL,
    mime_type character varying(128) NOT NULL,
    file_size bigint NOT NULL,
    storage_key text NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    to_delete boolean DEFAULT false NOT NULL,
    cloud_synced boolean DEFAULT true NOT NULL,
    CONSTRAINT files_file_name_check CHECK (((file_name)::text ~* '^[^\\/:\*\?"<>\|]{1,255}\.[a-z0-9]+$'::text))
);


--
-- Name: TABLE files; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.files IS '保存文件url (储存在云端) / guardar url de los archivos';


--
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_files (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    file_id bigint NOT NULL,
    sort smallint NOT NULL
);


--
-- Name: TABLE message_files; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.message_files IS '消息文件，音频，视频，视频 / los archivos de los mensajes';


--
-- Name: message_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.message_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    chat_panel_id bigint NOT NULL,
    sender_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    reply_to bigint DEFAULT '-1'::bigint,
    content text,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    is_read boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE messages; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.messages IS '聊天信息 / mensajes de chat';


--
-- Name: COLUMN messages.sender_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.sender_id IS '0代表发送者被删除都是还有人看消息所以保留消息';


--
-- Name: COLUMN messages.reply_to; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.messages.reply_to IS '-1代表引用的消息被删除';


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    title character varying(100) NOT NULL,
    message text NOT NULL,
    type smallint NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    click_action character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: COLUMN notifications.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.notifications.type IS '还不确定，应该有多种比如消息通知，减价，库存。。。';


--
-- Name: COLUMN notifications.click_action; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.notifications.click_action IS '导航到位置';


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_details (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    variant_product_id bigint,
    product_name character varying(100) NOT NULL,
    product_title character varying(150),
    product_code character varying(50) NOT NULL,
    variant_product_code character varying(50) NOT NULL,
    product_translations_snapshot jsonb DEFAULT '[]'::jsonb NOT NULL,
    variant_attributes_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    type_sale public."SaleVariant" NOT NULL,
    sale_unit_qty integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(14,6) NOT NULL,
    unit_price_iva numeric(14,6) NOT NULL,
    iva numeric(5,2) NOT NULL,
    subtotal numeric(20,2) NOT NULL,
    iva_total numeric(20,2) NOT NULL,
    total numeric(20,2) NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    CONSTRAINT order_details_amounts_check CHECK (((unit_price >= (0)::numeric) AND (unit_price_iva >= (0)::numeric) AND (iva >= (0)::numeric) AND (iva <= (100)::numeric) AND (subtotal >= (0)::numeric) AND (iva_total >= (0)::numeric) AND (total >= (0)::numeric))),
    CONSTRAINT order_details_quantity_check CHECK ((quantity >= 1)),
    CONSTRAINT order_details_sale_unit_qty_check CHECK ((sale_unit_qty >= 1))
);


--
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_pdf_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_pdf_files (
    order_id bigint NOT NULL,
    lang_code character varying(10) NOT NULL,
    file_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_series character varying(10) DEFAULT 'PED'::character varying NOT NULL,
    order_year smallint NOT NULL,
    order_sequence integer NOT NULL,
    order_number character varying(40) NOT NULL,
    retailer_id uuid,
    wholesaler_id uuid,
    status public."OrderStatus" DEFAULT 'PENDING'::public."OrderStatus" NOT NULL,
    currency character(3) DEFAULT 'EUR'::bpchar NOT NULL,
    subtotal numeric(20,2) NOT NULL,
    discount_total numeric(20,2) DEFAULT 0 NOT NULL,
    iva_total numeric(20,2) NOT NULL,
    total numeric(20,2) NOT NULL,
    item_count integer NOT NULL,
    shipping_address_snapshot jsonb NOT NULL,
    retailer_snapshot jsonb NOT NULL,
    wholesaler_snapshot jsonb NOT NULL,
    accepted_at timestamp without time zone,
    accepted_by uuid,
    rejected_at timestamp without time zone,
    rejected_by uuid,
    rejected_reason character varying(500),
    cancelled_at timestamp without time zone,
    estimated_delivery_date timestamp without time zone,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    cancelled_by uuid,
    cancelled_reason character varying(500),
    CONSTRAINT orders_amounts_check CHECK (((subtotal >= (0)::numeric) AND (discount_total >= (0)::numeric) AND (iva_total >= (0)::numeric) AND (total >= (0)::numeric))),
    CONSTRAINT orders_item_count_check CHECK ((item_count >= 1)),
    CONSTRAINT orders_rejected_reason_check CHECK (((status <> 'REJECTED'::public."OrderStatus") OR (rejected_reason IS NOT NULL))),
    CONSTRAINT orders_retailer_wholesaler_different CHECK (((retailer_id IS NULL) OR (wholesaler_id IS NULL) OR (retailer_id <> wholesaler_id))),
    CONSTRAINT orders_sequence_check CHECK ((order_sequence >= 1)),
    CONSTRAINT orders_year_check CHECK (((order_year >= 2000) AND (order_year <= 9999)))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_categories (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    is_primary boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE product_categories; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_categories IS '产品与分类的关联表，支持多对多关系。';


--
-- Name: COLUMN product_categories.is_primary; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.product_categories.is_primary IS '标记该关联是否为产品的主分类。';


--
-- Name: product_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_translations (
    product_id bigint NOT NULL,
    lang_code character varying(10) NOT NULL,
    name character varying(50) NOT NULL,
    title character varying(100),
    description text,
    name_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((name)::text)) STORED,
    title_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((title)::text)) STORED,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_by uuid
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    title character varying(100),
    description text,
    iva numeric(5,2) NOT NULL,
    status public."ProductStatus" DEFAULT 'ACTIVE'::public."ProductStatus" NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    product_code character varying(50) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    created_by uuid,
    updated_by uuid,
    name_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((name)::text)) STORED,
    title_unaccent text GENERATED ALWAYS AS (public.immutable_unaccent((title)::text)) STORED,
    version bigint DEFAULT 1 NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT products_iva_check CHECK (((iva >= (0)::numeric) AND (iva <= (100)::numeric)))
);


--
-- Name: TABLE products; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.products IS '产品基础表 / valor basica de productos';


--
-- Name: COLUMN products.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.status IS '1=activo, 0=desactivo';


--
-- Name: products_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_files (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    file_id bigint NOT NULL,
    sort smallint NOT NULL
);


--
-- Name: TABLE products_files; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.products_files IS '产品的宣传图什么的';


--
-- Name: products_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provinces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provinces (
    id integer NOT NULL,
    country_iso smallint NOT NULL,
    name character varying(100) NOT NULL,
    name_local character varying(100) NOT NULL
);


--
-- Name: COLUMN provinces.country_iso; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provinces.country_iso IS '所属国家 iso numeric，外键关联 countries 表';


--
-- Name: COLUMN provinces.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provinces.name IS '省份/州的英文名称';


--
-- Name: COLUMN provinces.name_local; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.provinces.name_local IS '省份/州的本地名称';


--
-- Name: provinces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.provinces_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: provinces_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.provinces_id_seq OWNED BY public.provinces.id;


--
-- Name: seq_admin_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_admin_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_deliveryman_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_deliveryman_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_retailer_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_retailer_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_superadmin_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_superadmin_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_support_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_support_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_warehouse_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_warehouse_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_wholesaler_id; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_wholesaler_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    session_id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    device_name character varying(150) NOT NULL,
    device_finger character varying(255) NOT NULL,
    user_agent text NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    last_ip character varying(50) NOT NULL,
    refresh_token text,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    last_active timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: user_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_uploads (
    user_id uuid NOT NULL,
    file_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user_id text,
    first_name character varying(50),
    last_name character varying(60),
    username character varying(50),
    password text NOT NULL,
    email character varying(255) NOT NULL,
    telephone character varying(25),
    status public."UserStatus" DEFAULT 'PENDING_VERIFICATION'::public."UserStatus" NOT NULL,
    profile jsonb,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    role public."UserRole" NOT NULL,
    tax_id character varying(20),
    updated_by uuid,
    profile_image_file_id bigint
);


--
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS '用户表';


--
-- Name: COLUMN users.role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.role IS '0 → wholesaler  批发商即本平台的商店，1 → retailer  零售商 2 → support  客服  3 → 送货员  5 → 货物管理员';


--
-- Name: COLUMN users.tax_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.tax_id IS '税号';


--
-- Name: variant_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.variant_products (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    product_id bigint NOT NULL,
    type_sale public."SaleVariant" NOT NULL,
    price numeric(14,6) NOT NULL,
    price_iva numeric(14,6) NOT NULL,
    available_stock integer NOT NULL,
    sort smallint NOT NULL,
    attributes jsonb,
    status public."ProductStatus" DEFAULT 'ACTIVE'::public."ProductStatus" NOT NULL,
    product_code character varying(50) NOT NULL,
    reserved_stock integer DEFAULT 0 NOT NULL,
    low_stock_threshold integer DEFAULT 0 NOT NULL,
    sale_unit_qty integer DEFAULT 1 NOT NULL,
    min_order_qty integer DEFAULT 1 NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT variant_available_stock_check CHECK ((available_stock >= 0)),
    CONSTRAINT variant_low_stock_threshold_check CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT variant_min_order_qty_check CHECK (((min_order_qty >= 1) AND (min_order_qty <= 1000000))),
    CONSTRAINT variant_price_check CHECK (((price >= (0)::numeric) AND (price <= 10000000.00))),
    CONSTRAINT variant_price_iva_check CHECK (((price_iva >= (0)::numeric) AND (price_iva <= 20000000.00))),
    CONSTRAINT variant_reserved_stock_check CHECK ((reserved_stock >= 0)),
    CONSTRAINT variant_sale_unit_qty_check CHECK (((sale_unit_qty >= 1) AND (sale_unit_qty <= 1000000))),
    CONSTRAINT variant_sort_check CHECK ((sort >= 0))
);


--
-- Name: TABLE variant_products; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.variant_products IS '变体销售配置';


--
-- Name: COLUMN variant_products.type_sale; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.type_sale IS '销售变体类型，分别为散卖，按包，按箱。';


--
-- Name: COLUMN variant_products.available_stock; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.available_stock IS '实际可供销售和发货的可用库存数量。';


--
-- Name: COLUMN variant_products.reserved_stock; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.reserved_stock IS '已下单但尚未发货的预留库存数量，避免超卖。';


--
-- Name: COLUMN variant_products.low_stock_threshold; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.low_stock_threshold IS '触发低库存预警的阈值。当可用库存低于此值时，向分销商发送通知。';


--
-- Name: COLUMN variant_products.sale_unit_qty; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.sale_unit_qty IS '一个销售单位（如：一箱、一包）所包含的最小库存单位数量。';


--
-- Name: COLUMN variant_products.min_order_qty; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.variant_products.min_order_qty IS '最小订购数量（以销售单位计）。';


--
-- Name: variant_products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.variant_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variant_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_tokens (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    is_used boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    attempts smallint DEFAULT 0 NOT NULL
);


--
-- Name: wholesaler_staffs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wholesaler_staffs (
    id bigint NOT NULL,
    wholesaler_id uuid NOT NULL,
    staff_user_id uuid NOT NULL,
    role public."UserRole" NOT NULL,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT chk_wholesaler_staff_not_self CHECK ((wholesaler_id <> staff_user_id)),
    CONSTRAINT chk_wholesaler_staff_role CHECK ((role = ANY (ARRAY['SUPPORT'::public."UserRole", 'DELIVERY'::public."UserRole", 'WAREHOUSE'::public."UserRole"])))
);


--
-- Name: wholesaler_staffs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wholesaler_staffs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wholesaler_staffs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities ALTER COLUMN id SET DEFAULT nextval('public.cities_id_seq'::regclass);


--
-- Name: provinces id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provinces ALTER COLUMN id SET DEFAULT nextval('public.provinces_id_seq'::regclass);


--
-- Name: cart_details cart_details_cart_variant_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT cart_details_cart_variant_unique UNIQUE (cart_id, variant_products_id);


--
-- Name: cart_details cart_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT cart_details_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: carts carts_user_wholesaler_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_user_wholesaler_unique UNIQUE (retailer_id, wholesaler_id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: chat_panels chat_panel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_panels
    ADD CONSTRAINT chat_panel_pkey PRIMARY KEY (id);


--
-- Name: chat_participants chat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_pkey PRIMARY KEY (chat_panel_id, user_id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: configurations configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_pkey PRIMARY KEY (user_id);


--
-- Name: countries countries_iso_alpha2_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_iso_alpha2_key UNIQUE (iso_alpha2);


--
-- Name: countries countries_iso_alpha3_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_iso_alpha3_key UNIQUE (iso_alpha3);


--
-- Name: countries countries_iso_numeric_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_iso_numeric_key UNIQUE (iso_numeric);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (iso_numeric);


--
-- Name: currencies currencies_iso_alpha3_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_iso_alpha3_key UNIQUE (iso_alpha3);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (iso_numeric);


--
-- Name: deliveries deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliveries
    ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);


--
-- Name: delivery_timeline delivery_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_timeline
    ADD CONSTRAINT delivery_timeline_pkey PRIMARY KEY (id);


--
-- Name: directions directions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_pkey PRIMARY KEY (id);


--
-- Name: discounts discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_pkey PRIMARY KEY (id);


--
-- Name: document_sequences document_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_sequences
    ADD CONSTRAINT document_sequences_pkey PRIMARY KEY (owner_id, document_type, year);


--
-- Name: files files_file_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_file_hash_key UNIQUE (file_hash);


--
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- Name: message_files message_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_files
    ADD CONSTRAINT message_files_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- Name: order_pdf_files order_pdf_files_order_lang_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_pdf_files
    ADD CONSTRAINT order_pdf_files_order_lang_unique UNIQUE (order_id, lang_code);


--
-- Name: order_pdf_files order_pdf_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_pdf_files
    ADD CONSTRAINT order_pdf_files_pkey PRIMARY KEY (order_id, file_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: orders orders_wholesaler_order_number_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_wholesaler_order_number_unique UNIQUE (wholesaler_id, order_number);


--
-- Name: orders orders_wholesaler_series_year_sequence_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_wholesaler_series_year_sequence_unique UNIQUE (wholesaler_id, order_series, order_year, order_sequence);


--
-- Name: verification_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: category_translations pk_category_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_translations
    ADD CONSTRAINT pk_category_translations PRIMARY KEY (category_id, lang_code);


--
-- Name: product_translations pk_product_translations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_translations
    ADD CONSTRAINT pk_product_translations PRIMARY KEY (product_id, lang_code);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: products_files products_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_files
    ADD CONSTRAINT products_files_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: provinces provinces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_pkey PRIMARY KEY (id);


--
-- Name: user_sessions unique_device_finger_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT unique_device_finger_user UNIQUE (user_id, device_finger);


--
-- Name: wholesaler_staffs uq_wholesaler_staff; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT uq_wholesaler_staff UNIQUE (wholesaler_id, staff_user_id);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id);


--
-- Name: user_uploads user_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_uploads
    ADD CONSTRAINT user_uploads_pkey PRIMARY KEY (user_id, file_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_key UNIQUE (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: variant_products variant_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.variant_products
    ADD CONSTRAINT variant_products_pkey PRIMARY KEY (id);


--
-- Name: wholesaler_staffs wholesaler_staffs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT wholesaler_staffs_pkey PRIMARY KEY (id);


--
-- Name: categories_name_unique_public; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX categories_name_unique_public ON public.categories USING btree (name) WHERE ((user_id IS NULL) AND (deleted_at IS NULL));


--
-- Name: categories_user_name_unique_private; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX categories_user_name_unique_private ON public.categories USING btree (user_id, name) WHERE ((user_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_cart_details_cart_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cart_details_cart_id ON public.cart_details USING btree (cart_id);


--
-- Name: idx_cart_details_variant_products_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cart_details_variant_products_id ON public.cart_details USING btree (variant_products_id);


--
-- Name: idx_carts_wholesaler_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carts_wholesaler_id ON public.carts USING btree (wholesaler_id);


--
-- Name: idx_categories_level_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_level_id ON public.categories USING btree (level, id);


--
-- Name: idx_categories_name_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_name_unaccent ON public.categories USING btree (lower(name_unaccent));


--
-- Name: idx_categories_name_unaccent_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_name_unaccent_trgm ON public.categories USING gin (name_unaccent public.gin_trgm_ops) WHERE (deleted_at IS NULL);


--
-- Name: idx_categories_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_parent_id ON public.categories USING btree (parent_id) WHERE (deleted_at IS NULL);


--
-- Name: idx_categories_parent_id_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_parent_id_id ON public.categories USING btree (parent_id, id);


--
-- Name: idx_categories_private_user_level_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_private_user_level_name ON public.categories USING btree (user_id, level, name) WHERE ((user_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_categories_private_user_parent_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_private_user_parent_name ON public.categories USING btree (user_id, parent_id, name) WHERE ((user_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_categories_public_level_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_public_level_name ON public.categories USING btree (level, name) WHERE ((user_id IS NULL) AND (deleted_at IS NULL));


--
-- Name: idx_categories_public_parent_level_name_all; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_public_parent_level_name_all ON public.categories USING btree (parent_id, level, name) WHERE (user_id IS NULL);


--
-- Name: idx_categories_public_parent_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_public_parent_name ON public.categories USING btree (parent_id, name) WHERE ((user_id IS NULL) AND (deleted_at IS NULL));


--
-- Name: idx_categories_user_parent_level_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_categories_user_parent_level_name ON public.categories USING btree (user_id, parent_id, level, name);


--
-- Name: idx_category_translations_category_lang; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_category_translations_category_lang ON public.category_translations USING btree (category_id, lang_code);


--
-- Name: idx_category_translations_lang_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_category_translations_lang_code ON public.category_translations USING btree (lang_code);


--
-- Name: idx_category_translations_name_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_category_translations_name_unaccent ON public.category_translations USING btree (lower(name_unaccent));


--
-- Name: idx_category_translations_name_unaccent_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_category_translations_name_unaccent_trgm ON public.category_translations USING gin (name_unaccent public.gin_trgm_ops);


--
-- Name: idx_files_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_files_created_at ON public.files USING btree (created_at);


--
-- Name: idx_message_files_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_message_files_file_id ON public.message_files USING btree (file_id);


--
-- Name: idx_order_details_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_details_order_id ON public.order_details USING btree (order_id);


--
-- Name: idx_order_pdf_files_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_pdf_files_file_id ON public.order_pdf_files USING btree (file_id);


--
-- Name: idx_order_pdf_files_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_pdf_files_order_id ON public.order_pdf_files USING btree (order_id);


--
-- Name: idx_orders_order_number; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_order_number ON public.orders USING btree (order_number);


--
-- Name: idx_orders_retailer_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_retailer_created_at ON public.orders USING btree (retailer_id, created_at DESC);


--
-- Name: idx_orders_wholesaler_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_wholesaler_created_at ON public.orders USING btree (wholesaler_id, created_at DESC);


--
-- Name: idx_orders_wholesaler_status_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_wholesaler_status_created_at ON public.orders USING btree (wholesaler_id, status, created_at DESC);


--
-- Name: idx_product_categories_category_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_categories_category_id ON public.product_categories USING btree (category_id);


--
-- Name: idx_product_categories_category_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_categories_category_product ON public.product_categories USING btree (category_id, product_id);


--
-- Name: idx_product_categories_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_categories_product_id ON public.product_categories USING btree (product_id);


--
-- Name: idx_product_translations_name_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_translations_name_unaccent ON public.product_translations USING btree (lower(name_unaccent));


--
-- Name: idx_product_translations_title_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_translations_title_unaccent ON public.product_translations USING btree (lower(title_unaccent));


--
-- Name: idx_products_files_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_files_file_id ON public.products_files USING btree (file_id);


--
-- Name: idx_products_files_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_files_product_id ON public.products_files USING btree (product_id);


--
-- Name: idx_products_name_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_name_unaccent ON public.products USING btree (lower(name_unaccent));


--
-- Name: idx_products_status_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_status_id ON public.products USING btree (status, id);


--
-- Name: idx_products_title_unaccent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_title_unaccent ON public.products USING btree (lower(title_unaccent));


--
-- Name: idx_products_user_id_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_user_id_id ON public.products USING btree (user_id, id);


--
-- Name: idx_products_user_status_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_user_status_id ON public.products USING btree (user_id, status, id);


--
-- Name: idx_users_wholesaler_active_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_wholesaler_active_id ON public.users USING btree (id) WHERE ((role = 'WHOLESALER'::public."UserRole") AND (status <> ALL (ARRAY['PENDING_REVIEW'::public."UserStatus", 'PENDING_VERIFICATION'::public."UserStatus", 'BANNED'::public."UserStatus", 'INACTIVE'::public."UserStatus"])));


--
-- Name: idx_variant_products_product_id_price_iva; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_variant_products_product_id_price_iva ON public.variant_products USING btree (product_id, price_iva);


--
-- Name: idx_wholesaler_staffs_staff_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wholesaler_staffs_staff_user_id ON public.wholesaler_staffs USING btree (staff_user_id);


--
-- Name: idx_wholesaler_staffs_wholesaler_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wholesaler_staffs_wholesaler_id ON public.wholesaler_staffs USING btree (wholesaler_id);


--
-- Name: idx_wholesaler_staffs_wholesaler_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wholesaler_staffs_wholesaler_role ON public.wholesaler_staffs USING btree (wholesaler_id, role);


--
-- Name: password_reset_tokens_token_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX password_reset_tokens_token_idx ON public.verification_tokens USING btree (token);


--
-- Name: password_reset_tokens_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX password_reset_tokens_user_id_idx ON public.verification_tokens USING btree (user_id);


--
-- Name: verification_tokens_user_id_token_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_tokens_user_id_token_idx ON public.verification_tokens USING btree (user_id, token);


--
-- Name: users trg_generate_user_id; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_generate_user_id BEFORE UPDATE OF status ON public.users FOR EACH ROW EXECUTE FUNCTION public.generate_user_id();


--
-- Name: cart_details cart_details_cart_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT cart_details_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id) ON DELETE CASCADE;


--
-- Name: cart_details cart_details_variant_products_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_details
    ADD CONSTRAINT cart_details_variant_products_id_fkey FOREIGN KEY (variant_products_id) REFERENCES public.variant_products(id) ON DELETE CASCADE;


--
-- Name: carts carts_retailer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_retailer_id_fkey FOREIGN KEY (retailer_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: carts carts_wholesaler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_wholesaler_id_fkey FOREIGN KEY (wholesaler_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: categories categories_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: categories categories_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- Name: categories categories_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: categories categories_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: category_translations category_translations_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_translations
    ADD CONSTRAINT category_translations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: chat_participants chat_participants_chat_panel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_chat_panel_id_fkey FOREIGN KEY (chat_panel_id) REFERENCES public.chat_panels(id) ON DELETE CASCADE;


--
-- Name: chat_participants chat_participants_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_participants
    ADD CONSTRAINT chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: cities cities_province_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_province_id_fkey FOREIGN KEY (province_id) REFERENCES public.provinces(id) ON DELETE CASCADE;


--
-- Name: configurations configurations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configurations
    ADD CONSTRAINT configurations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: countries countries_currency_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(iso_numeric) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: deliveries deliveries_delivery_person_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliveries
    ADD CONSTRAINT deliveries_delivery_person_fkey FOREIGN KEY (delivery_person) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: delivery_timeline delivery_timeline_delivery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_timeline
    ADD CONSTRAINT delivery_timeline_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id) ON DELETE CASCADE;


--
-- Name: directions directions_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE RESTRICT;


--
-- Name: directions directions_country_iso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_country_iso_fkey FOREIGN KEY (country_iso) REFERENCES public.countries(iso_numeric) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: directions directions_province_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_province_id_fkey FOREIGN KEY (province_id) REFERENCES public.provinces(id) ON DELETE RESTRICT;


--
-- Name: directions directions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: discounts discounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: document_sequences document_sequences_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_sequences
    ADD CONSTRAINT document_sequences_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: category_translations fk_category_translations_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_translations
    ADD CONSTRAINT fk_category_translations_category_id FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- Name: product_translations fk_product_translations_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_translations
    ADD CONSTRAINT fk_product_translations_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: user_sessions fk_user_sessions_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT fk_user_sessions_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: message_files message_files_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_files
    ADD CONSTRAINT message_files_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE;


--
-- Name: message_files message_files_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_files
    ADD CONSTRAINT message_files_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: messages messages_chat_panel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_chat_panel_id_fkey FOREIGN KEY (chat_panel_id) REFERENCES public.chat_panels(id) ON DELETE CASCADE;


--
-- Name: messages messages_reply_to_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_reply_to_fkey FOREIGN KEY (reply_to) REFERENCES public.messages(id) ON DELETE SET DEFAULT;


--
-- Name: messages messages_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE SET DEFAULT;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: order_details order_details_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: order_details order_details_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;


--
-- Name: order_details order_details_variant_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_variant_product_id_fkey FOREIGN KEY (variant_product_id) REFERENCES public.variant_products(id) ON DELETE SET NULL;


--
-- Name: order_pdf_files order_pdf_files_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_pdf_files
    ADD CONSTRAINT order_pdf_files_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE;


--
-- Name: order_pdf_files order_pdf_files_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_pdf_files
    ADD CONSTRAINT order_pdf_files_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: orders orders_accepted_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: orders orders_cancelled_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: orders orders_rejected_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: orders orders_retailer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_retailer_id_fkey FOREIGN KEY (retailer_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: orders orders_wholesaler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_wholesaler_id_fkey FOREIGN KEY (wholesaler_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: verification_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: product_categories product_categories_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;


--
-- Name: product_categories product_categories_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_translations product_translations_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_translations
    ADD CONSTRAINT product_translations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: products products_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: products_files products_files_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_files
    ADD CONSTRAINT products_files_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE;


--
-- Name: products_files products_files_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_files
    ADD CONSTRAINT products_files_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: products products_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: products products_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: provinces provinces_country_iso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_country_iso_fkey FOREIGN KEY (country_iso) REFERENCES public.countries(iso_numeric) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_uploads user_uploads_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_uploads
    ADD CONSTRAINT user_uploads_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE;


--
-- Name: user_uploads user_uploads_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_uploads
    ADD CONSTRAINT user_uploads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: users users_profile_image_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_profile_image_file_id_fkey FOREIGN KEY (profile_image_file_id) REFERENCES public.files(id) ON DELETE SET NULL;


--
-- Name: variant_products variant_products_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.variant_products
    ADD CONSTRAINT variant_products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: variant_products variant_products_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.variant_products
    ADD CONSTRAINT variant_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: variant_products variant_products_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.variant_products
    ADD CONSTRAINT variant_products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: wholesaler_staffs wholesaler_staffs_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT wholesaler_staffs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: wholesaler_staffs wholesaler_staffs_staff_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT wholesaler_staffs_staff_user_id_fkey FOREIGN KEY (staff_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: wholesaler_staffs wholesaler_staffs_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT wholesaler_staffs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: wholesaler_staffs wholesaler_staffs_wholesaler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wholesaler_staffs
    ADD CONSTRAINT wholesaler_staffs_wholesaler_id_fkey FOREIGN KEY (wholesaler_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: cart_details; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cart_details ENABLE ROW LEVEL SECURITY;

--
-- Name: carts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

--
-- Name: configurations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.configurations ENABLE ROW LEVEL SECURITY;

--
-- Name: deliveries; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;

--
-- Name: delivery_timeline; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.delivery_timeline ENABLE ROW LEVEL SECURITY;

--
-- Name: document_sequences; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.document_sequences ENABLE ROW LEVEL SECURITY;

--
-- Name: messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

--
-- Name: notifications; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

--
-- Name: order_details; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.order_details ENABLE ROW LEVEL SECURITY;

--
-- Name: order_pdf_files; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.order_pdf_files ENABLE ROW LEVEL SECURITY;

--
-- Name: orders; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

--
-- Name: user_sessions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- Name: verification_tokens; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.verification_tokens ENABLE ROW LEVEL SECURITY;

--
-- Name: wholesaler_staffs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.wholesaler_staffs ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict RoDyhYsshoz4OnbrfFPJckgV42RIOPaHefEDAhyKguQoOldSiPYFVafFZHylDjF

