export enum OrderSortByEnums {
  ORDER_DATE = 'ORDER_DATE',
  ORDER_NUMBER = 'ORDER_NUMBER',
  ORDER_DELIVERY_DATE = 'ORDER_DELIVERY_DATE',
  TOTAL_PRICE = 'TOTAL_PRICE',
  TOTAL_IVA = 'TOTAL_IVA',
  TOTAL_SUBTOTAL = 'TOTAL_SUBTOTAL',
  TOTAL_ITEM = 'TOTAL_ITEM',
}
