export const CART_ERRORS = {
  VARIANT_NOT_FOUND_OR_INVALID: 'VARIANT_NOT_FOUND_OR_INVALID',
  QUANTITY_BELOW_MIN_ORDER: 'QUANTITY_BELOW_MIN_ORDER',
  NOT_ENOUGH_STOCK: 'NOT_ENOUGH_STOCK',
} as const;
