export const CART_ERRORS = {
  VARIANT_NOT_FOUND_OR_INVALID: 'VARIANT_NOT_FOUND_OR_INVALID',
  QUANTITY_BELOW_MIN_ORDER: 'QUANTITY_BELOW_MIN_ORDER',
  NOT_ENOUGH_STOCK: 'NOT_ENOUGH_STOCK',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
} as const;

export const CART_ITEM_STATUS = {
  AVAILABLE: 'AVAILABLE',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  VARIANT_INACTIVE: 'VARIANT_INACTIVE',
  BELOW_MIN_ORDER_QTY: 'BELOW_MIN_ORDER_QTY',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  WHOLESALER_UNAVAILABLE: 'WHOLESALER_UNAVAILABLE',
} as const;

export type CartItemStatus =
  (typeof CART_ITEM_STATUS)[keyof typeof CART_ITEM_STATUS];

export const CART_GROUP_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HAS_INVALID_ITEMS: 'HAS_INVALID_ITEMS',
  BELOW_MINIMUM_ORDER_AMOUNT: 'BELOW_MINIMUM_ORDER_AMOUNT',
};

export type CartGroupStatus =
  (typeof CART_GROUP_STATUS)[keyof typeof CART_GROUP_STATUS];
