allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true
overrides:
  "html-minifier": "npm:html-minifier-terser@^6.1.0"
  "hono": "^4.11.4"
  "diff": "^8.0.3"
  "picomatch": "^4.0.4"
  "typescript": "$typescript"
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - msgpackr-extract
  - nestjs-pino
  - prisma
  - unrs-resolver
